### PR TITLE
Add bangladeshi currency support

### PR DESCRIPTION
**Pull request by SaiferGit**
Create new locale **en-BD** for bangladeshi currency BDT
Include **en-BD** inside `getLocaleClass` method of to-words.ts class

### CODE REVIEW

**Comment by SaiferGit** [comment]
@mastermunj please have a look into this PR

**Comment by mastermunj** [comment]
Thank you @SaiferGit . You will need to add test file for the locale.

**Comment by SaiferGit** [comment]
> Thank you @SaiferGit . You will need to add test file for the locale.

Added successfully. @mastermunj

**Comment by mastermunj** [comment]
@SaiferGit Thank you. The tests are clearing. Please help remove .idea directory to be able to merge this PR.

**Comment by SaiferGit** [comment]
> @SaiferGit Thank you. The tests are passing. Please help remove .idea directory to be able to merge this PR.

@mastermunj removed successfully.

**Comment by mastermunj** [comment]
Thank you!. Released 3.0.2 with the changes.

**Pull request merged**
