### PR TITLE
feat: support added for french (fr-FR) in src

### PR DESCRIPTION
**Pull request by ZlFlo74**
Locale + Tests + 3 options (especially for plural). As a result, docs updated.
dist folder not updated in this request.

### CODE REVIEW

**Comment by ZlFlo74** [comment]
I tried to update dist/ folder, but the husky pre-commit hook gave me that warning for my new .d.ts files :
`0:0  warning  File ignored because of a matching ignore pattern. Use "--no-ignore" to override`
And the eslint flag --max-warnings=0 obviously raise an error and block my commit.
I can't see how to update the dist/ folder. Maybe you can help me ?

**Comment by mastermunj** [comment]
Hi, Thank you for the PR.

I will look into the error you are facing.

**Comment by mastermunj** [comment]
Hi @ZlFlo74, please sync your repo and try again. The error should go away. Let me know if any issue occurs.

**Comment by ZlFlo74** [comment]
It worked, thanks. I opened a new PR with the working new feature.

**Pull request closed without merging**
