### PR TITLE
Add support for euros

### PR DESCRIPTION
**Pull request by hardiksondagar**

### CODE REVIEW

**Comment by mastermunj** [comment]
Thank you for the PR @hardiksondagar, however, EU isn't a valid country/region code.

https://support.google.com/webmasters/thread/189812796/should-i-set-en-eu-in-hreflang-for-europe?hl=en

**Comment by hardiksondagar** [comment]
@mastermunj what would you suggest for the `localecode`? We need `euro` currency support for our text-to-speech API as our current `tts` engine doesn't work well with currency numbers.

**Comment by mastermunj** [comment]
Two options:
1. Pick any of the EU countries in the eurozone and create a locale.
2. Try overriding the currency options
```ts
const toWords = new ToWords({
  localeCode: 'en-US',
  converterOptions: {
    currency: true,
    ignoreDecimal: false,
    ignoreZeroCurrency: false,
    doNotAddOnly: false,
    currencyOptions: { // can be used to override defaults for the selected locale
      name: 'Euro',
      plural: 'Euros',
      symbol: '€',
      fractionalUnit: {
        name: 'Eurocent',
        plural: 'Eurocents',
        symbol: '¢',
      },
    }
  }
});
```

**Comment by hardiksondagar** [comment]
@mastermunj I am going with option 1 with the `en-IE` locale. 
Closing this PR and raising a separate one here https://github.com/mastermunj/to-words/pull/1475

**Pull request closed without merging**
