### PR TITLE
Added support for Philippine currency

### PR DESCRIPTION
**Pull request by eta1993**

### CODE REVIEW

**Comment by mastermunj** [comment]
Thank you for the PR @eta1993.

Please help update the README.md

**Comment by eta1993** [comment]
> Thank you for the PR @eta1993.
> 
> Please help update the README.md

Done

**Comment by mastermunj** [comment]
> > Thank you for the PR @eta1993.
> > Please help update the README.md
> 
> Done

The changes are not visible in the file list.

**Comment by eta1993** [comment]
Do you mean this one?

to-words-files-changed

**Comment by mastermunj** [comment]
Hi @eta1993 , I am referring to the changes in the https://github.com/mastermunj/to-words/blob/main/README.md file.

**Comment by eta1993** [comment]
> Hi @eta1993 , I am referring to the changes in the https://github.com/mastermunj/to-words/blob/main/README.md file.

Committed the fix to README.md. Done

**Comment by mastermunj** [comment]
Thank you, @eta1993. Released the changes with v3.6.1

**Pull request merged**
