### PR TITLE
Support for singluar currency word

### PR DESCRIPTION
**Pull request by hardiksondagar**
Added support for singular suffix for currency.

Eg.
```
$1 -> One Dollar Only (instead of One Dollars Only)
$1.01 -> One Dollar and One Cent Only (instead of One Dollars and One Cents Only)
```

## My conversation with ChatGPT
```
[me]
---
Q. Which one is accurate grammatically? zero rupee or zero rupees?


[chatgpt]
---
A. In English grammar, when referring to a quantity of zero, it's common to use the plural form of count nouns. 
Therefore, the correct and widely used phrase would be "zero rupees," not "zero rupee." 
The same rule applies to other currencies and count nouns in general. 

Here are some examples with other popular currencies and different decimal values:

1. **Rupees (INR, Indian Rupee)**:
   - Zero rupees (₹0)
   - ₹0.50 is pronounced as "fifty paise" (since 1 rupee = 100 paise)

2. **Dollars (USD, US Dollar)**:
   - Zero dollars ($0)
   - $0.25 is pronounced as "twenty-five cents" (since 1 dollar = 100 cents)

3. **Euros (EUR, Euro)**:
   - Zero euros (€0)
   - €0.75 is pronounced as "seventy-five cents" or "seventy-five euro cents"

4. **Pounds (GBP, British Pound Sterling)**:
   - Zero pounds (£0)
   - £0.10 is pronounced as "ten pence" (since 1 pound = 100 pence)

5. **Yen (JPY, Japanese Yen)**:
   - Zero yen (¥0)
   - ¥0.00 is still zero yen, as the yen does not commonly use smaller units in everyday transactions.

In each case, when the value is zero, the plural form of the currency is used. 

For fractional amounts, the smaller unit of the currency is typically named (like paise, cents, pence) and is usually pronounced in its plural form if the amount is more than one.

[me]
---
Q. Any place where either rupee or paisa is used?


[chatgpt]
---
A. In the context of Indian currency, the terms "rupee" and "paisa" are used in singular or plural forms based on the specific quantity they refer to. Here are some scenarios where either "rupee" or "paisa" might be used:

1. **Rupee (Singular and Plural)**:
   - Singular: When referring to one unit of currency, you would say "one rupee."
   - Plural: For any quantity more than one, you use "rupees." For example, "five rupees," "twenty rupees," etc.

2. **Paisa (Singular and Plural)**:
   - Singular: Similarly, when referring to exactly one-hundredth of a rupee, you would say "one paisa."
   - Plural: When referring to more than one-hundredth of a rupee, you use "paise." For example, "fifty paise," "seventy-five paise," etc.

The use of "paisa" is less common in everyday transactions now due to the low value of a single paisa.
However, it's still used in formal and financial contexts, particularly in accounting, pricing, and financial statements where exact amounts are important. 

When the amount is zero, the plural forms "rupees" and "paise" are typically used, as in "zero rupees" or "zero paise." This follows the general rule in English grammar for using plural forms with the number zero.

```

### CODE REVIEW

**Comment by hardiksondagar** [comment]
@mastermunj I have covered only `en-IN`, `en-US`, and `en-GB`. If the proposed changes look okay, I will add other locales.

**Comment by mastermunj** [comment]
@hardiksondagar please go ahead.

**Comment by hardiksondagar** [comment]
> @hardiksondagar please go ahead.

@mastermunj I have covered the remaining locales.

**Comment by mastermunj** [comment]
Thank you @hardiksondagar. Please help rebase with the main so that en-IE also gets covered.

**Comment by hardiksondagar** [comment]
> Thank you @hardiksondagar. Please help rebase with the main so that en-IE also gets covered.

Just did that @mastermunj

**Comment by mastermunj** [comment]
Somehow the changes aren't visible. I am unable to find en-IE with relevant changes in the file list.

**Comment by hardiksondagar** [comment]
> Somehow the changes aren't visible. I am unable to find en-IE with relevant changes in the file list.

@mastermunj I have synched your main branch to my feature branch here [37b3564](https://github.com/mastermunj/to-words/pull/1470/commits/37b35647e91e2a3dba77d86a79078e36d84948c6)

```
Merge branch 'mastermunj:main' into singular-currency-support
```

**Comment by mastermunj** [comment]
The file en-IE is still not visible in the files list. You can check at https://github.com/mastermunj/to-words/pull/1470/files

**Comment by hardiksondagar** [comment]
> The file en-IE is still not visible in the files list. You can check at https://github.com/mastermunj/to-words/pull/1470/files
> 
> Instead of merging, try doing a rebase. Also, please run the test suite locally as I believe it should fail for en-IE if it's not updated.

Hi @mastermunj I have attempted to do the rebase now. I am unfamiliar with rebase, so please guide me if I have not done it the right way.

**Review by mastermunj — APPROVED** [review]

**Comment by mastermunj** [comment]
Thank you, @hardiksondagar. Released this as v4

**Pull request merged**
